info:
    version: ""
    title: data_source_huaweicloud_apig_environments
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/envs:
        GET:
            tag: APIG
