info:
    version: ""
    title: data_source_huaweicloud_fgs_application_templates
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: FunctionGraph
paths:
    /v2/{project_id}/fgs/application/templates:
        GET:
            tag: FunctionGraph
