info:
    version: ""
    title: resource_huaweicloud_fgs_async_invoke_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: FunctionGraph
paths:
    /v2/{project_id}/fgs/functions/{function_urn}/async-invoke-config:
        DELETE:
            tag: FunctionGraph
        GET:
            tag: FunctionGraph
        PUT:
            tag: FunctionGraph
