info:
    version: ""
    title: resource_huaweicloud_codearts_deploy_application
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CodeArtsDeploy
paths:
    /v1/applications:
        POST:
            tag: CodeArtsDeploy
    /v1/applications/{app_id}:
        DELETE:
            tag: CodeArtsDeploy
    /v1/applications/{app_id}/info:
        GET:
            tag: CodeArtsDeploy
