info:
    version: ""
    title: resource_huaweicloud_servicestage_environment
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ServiceStage
paths:
    /v2/{project_id}/cas/environments:
        POST:
            tag: ServiceStage
    /v2/{project_id}/cas/environments/{envId}:
        DELETE:
            tag: ServiceStage
        GET:
            tag: ServiceStage
        PUT:
            tag: ServiceStage
    /v2/{project_id}/cas/environments/{envId}/resources:
        PATCH:
            tag: ServiceStage
