info:
    version: ""
    title: resource_huaweicloud_apig_application
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/apps:
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/apps/{app_id}:
        DELETE:
            tag: APIG
        GET:
            tag: APIG
        PUT:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/apps/{app_id}/app-codes:
        GET:
            tag: APIG
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/apps/{app_id}/app-codes/{app_code_id}:
        DELETE:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/apps/secret/{app_id}:
        PUT:
            tag: APIG
