info:
    version: ""
    title: resource_huaweicloud_apig_environment
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/envs:
        GET:
            tag: APIG
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instance_id}/envs/{env_id}:
        DELETE:
            tag: APIG
        PUT:
            tag: APIG
