info:
    version: ""
    title: resource_huaweicloud_lts_structuring_custom_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: LTS
paths:
    /v2/{project_id}/lts/struct/template:
        DELETE:
            tag: LTS
        GET:
            tag: LTS
        POST:
            tag: LTS
        PUT:
            tag: LTS
