info:
    version: ""
    title: resource_huaweicloud_apig_application_authorization
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instanceId}/app-auths:
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/app-auths/{authId}:
        DELETE:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/app-auths/binded-apis:
        GET:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/app-auths/unbinded-apis:
        GET:
            tag: APIG
