info:
    version: ""
    title: resource_huaweicloud_as_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: AS
paths:
    /autoscaling-api/v1/{project_id}/scaling_configuration:
        POST:
            tag: AS
    /autoscaling-api/v1/{project_id}/scaling_configuration/{id}:
        DELETE:
            tag: AS
        GET:
            tag: AS
    /autoscaling-api/v1/{project_id}/scaling_group:
        GET:
            tag: AS
