info:
    version: ""
    title: resource_huaweicloud_apig_application
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instanceId}/apps:
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/apps/{appId}:
        DELETE:
            tag: APIG
        GET:
            tag: APIG
        PUT:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/apps/{appId}/app-codes:
        GET:
            tag: APIG
        POST:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/apps/{appId}/app-codes/{codeId}:
        DELETE:
            tag: APIG
    /v2/{project_id}/apigw/instances/{instanceId}/apps/secret/{appId}:
        PUT:
            tag: APIG
