info:
    version: ""
    title: resource_huaweicloud_apig_instance_routes
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/features:
        GET:
            tag: APIG
        POST:
            tag: APIG
